# Generated by Django 5.0.2 on 2024-03-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_cities', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('type_of_software', models.CharField(default=False, max_length=200)),
                ('contact_telephone_no', models.CharField(default=False, max_length=200)),
                ('vendor_id', models.PositiveIntegerField()),
                ('website', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=50)),
                ('description', models.CharField(default=False, max_length=500)),
                ('software_name', models.CharField(max_length=50)),
                ('company_established', models.PositiveIntegerField(default=False)),
                ('no_of_employees', models.PositiveIntegerField(default=False)),
                ('internal_professional_services', models.CharField(default=False, max_length=3)),
                ('last_demo_date', models.CharField(default=False, max_length=20)),
                ('last_reviewed_date', models.CharField(max_length=20)),
                ('business_areas', models.CharField(default=False, max_length=200)),
                ('modules', models.CharField(max_length=50)),
                ('financial_services_client_types', models.CharField(default=False, max_length=100)),
                ('cloud_type', models.CharField(blank=True, choices=[('cloud_native', 'cloud_native'), ('cloud_based', 'cloud_based'), ('cloud_enabled', 'cloud_enabled')], max_length=200, null=True)),
                ('additional_info', models.CharField(default=False, max_length=500)),
                ('document_to_attach', models.FileField(default=False, max_length=3, upload_to='')),
            ],
        ),
    ]
