# Generated by Django 5.0.2 on 2024-02-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=False, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
