# Generated by Django 5.0.2 on 2024-02-17 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_address', models.TextField()),
                ('phone_number', models.CharField(max_length=200)),
                ('vendor_id', models.PositiveIntegerField()),
                ('website', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=50)),
                ('detailed_description', models.CharField(default=False, max_length=500)),
                ('company_name', models.CharField(max_length=50)),
                ('software_name', models.CharField(max_length=50)),
                ('company_established', models.PositiveIntegerField(default=False)),
                ('location_countries', models.CharField(max_length=500)),
                ('location_cities', models.CharField(max_length=100)),
                ('address', models.CharField(default=False, max_length=100)),
                ('internal_professional_services', models.CharField(max_length=3)),
                ('last_reviewed_date', models.CharField(max_length=20)),
                ('business_areas', models.CharField(default=False, max_length=200)),
                ('modules', models.CharField(max_length=50)),
                ('financial_services_client_types', models.CharField(default=False, max_length=100)),
                ('additional_info', models.CharField(default=False, max_length=500)),
                ('doc_to_attach', models.CharField(default=False, max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
