# Generated by Django 5.0.2 on 2024-02-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='detailed_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='doc_to_attach',
            new_name='document_to_attach',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='vendor',
            name='cloud_type',
            field=models.CharField(blank=True, choices=[('cloud_native', 'cloud_native'), ('cloud_based', 'cloud_based'), ('cloud_enabled', 'cloud_enabled')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_telephone_no',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='last_demo_date',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='no_of_employees',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='type_of_software',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='internal_professional_services',
            field=models.CharField(default=False, max_length=3),
        ),
    ]
