# Generated by Django 5.0.2 on 2024-02-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='document_to_attach',
            field=models.FileField(default=False, max_length=3, upload_to=''),
        ),
    ]
