# Generated by Django 5.0.2 on 2024-03-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_vendor_document_to_attach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='business_areas',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='cloud_type',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='company_established',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='contact_telephone_no',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='document_to_attach',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='financial_services_client_types',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='internal_professional_services',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='last_demo_date',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='last_reviewed_date',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='location_cities',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='modules',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='no_of_employees',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='software_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='type_of_software',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='website',
        ),
    ]
